export const LOAD_PERSONAJES = 'LOAD_PERSONAJES';
export const LOAD_PERSONAJES_SUCCESS = 'LOAD_PERSONAJES_SUCCESS';

export const LOAD_PERSONAJE = 'LOAD_PERSONAJE';
export const LOAD_PERSONAJE_SUCCESS = 'LOAD_PERSONAJE_SUCCESS';